dataset_path: TainU/LSDBench
dataset_kwargs:
  token: True
  cache_dir: lsdbench
  video: True
task: lsdbench
test_split: test
output_type: generate_until
doc_to_visual: !function utils.lsdbench_doc_to_visual
doc_to_text: !function utils.lsdbench_doc_to_text
doc_to_target: "correct_answer"
generation_kwargs:
  max_new_tokens: 512
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.lsdbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.lsdbench_aggregate_accuracy_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0

